# These are supported funding model platforms

[<img src="https://img.buymeacoffee.com/button-api/?text=Regálame un cafe&emoji=&slug=jonorozcoc&button_colour=FFDD00&font_colour=000000&font_family=Poppins&outline_colour=000000&coffee_colour=ffffff">](https://www.buymeacoffee.com/jonorozcoc)
